// Generated by video-domain; do not edit.
export type Track = {
  id: string;
  kind: string;
  label: string;
  language: string | null;
  bandwidth: number | null;
  resolution: string | null;
  codecs: string | null;
  audioGroup: string | null;
};
export type Inspection = {
  id: string;
  title: string;
  provider: string;
  duration: number;
  videoTracks: Array<Track>;
  audioTracks: Array<Track>;
  subtitleTracks: Array<Track>;
};
export type DownloadOptions = {
  inspectionId: string;
  videoId: string;
  audioId: string | null;
  subtitleId: string | null;
  subtitleMode: string;
  subtitleOffset: number;
  outputDir: string;
  filename: string;
  format: string;
};
export type Job = {
  id: string;
  title: string;
  provider: string;
  state: string;
  stage: string;
  revision: number;
  createdAt: number;
  updatedAt: number;
  downloadedBytes: number;
  estimatedTotalBytes: number | null;
  completedSegments: number;
  totalSegments: number;
  speed: number;
  eta: number | null;
  duration: number;
  output: string | null;
  error: string | null;
  errorCode: string | null;
  options: DownloadOptions;
};
export type Settings = {
  outputDir: string;
  cacheDir: string;
  concurrency: number;
  keepCache: boolean;
  theme: string;
};
export type RuntimeStatus = {
  ffmpeg: boolean;
  ffprobe: boolean;
  ffmpegVersion: string;
  dataDir: string;
};
