CREATE TABLE jobs (id TEXT PRIMARY KEY, payload TEXT NOT NULL, updated REAL NOT NULL);
CREATE TABLE job_sources (job_id TEXT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE, source TEXT NOT NULL);
CREATE TABLE settings (id INTEGER PRIMARY KEY CHECK(id=1), payload TEXT NOT NULL);
CREATE TABLE segments (job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, stable_id TEXT NOT NULL, bytes INTEGER NOT NULL, checksum TEXT NOT NULL, PRIMARY KEY(job_id,stable_id));
